name: Build APK  
on: [push, pull_request]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
  
      - name: Buildozer Action  
        uses: ArtemSerebriennikov/buildozer-action@v1  
        with:  
          workdir: .  
          buildozer_version: master  
  
      - name: Upload APK  
        uses: actions/upload-artifact@v3  
        with:  
          name: my-app-apk  
          path: bin/* .apk
